### ISSUE TITLE
withBeta headers not applied when not using tools

### ISSUE THREAD

**Issue by psykhi** [liushuangls/go-anthropic#2]
Anthropic just released a new beta header `max-tokens-3-5-sonnet-2024-07-15` that allows clients to request up to 8192 completion tokens from the claude API with Sonnet 3.5.

The problem is that the package only appends this header if we're using tools : https://github.com/liushuangls/go-anthropic/blob/60c42fe9cd6b6dd18066e8326c8a9606c2366d0c/message_stream.go#L89

https://github.com/liushuangls/go-anthropic/blob/60c42fe9cd6b6dd18066e8326c8a9606c2366d0c/message.go#L264

I don't have the full context but I think these checks should be removed and the beta headers always added?

**Comment by liushuangls** [comment]
Thank you for bringing up this issue. It has now been updated to always include beta headers.

**Comment by psykhi** [comment]
Thanks a lot!
